const BASE_URL = "http://localhost:3000/";
export const registrationURL = `${BASE_URL}api/registration`;
export const loginURL = `${BASE_URL}api/login`;
export const refreshTokenURL = `${BASE_URL}api/refresh`;
export const generateNewEmail = `${BASE_URL}api/genereteMail`;
export const getMailScore = `${BASE_URL}api/emailScore`;
export const upgradeLimit = `${BASE_URL}api/upgradeLimit`;
export const addIdentities = `${BASE_URL}api/addIdentity`;
export const getIdentities = `${BASE_URL}api/getIdentites`;
